apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
      - name: todo-web
        image: shahood2000/postgres:latest  # Replace with your image name
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-service.default.svc.cluster.local"  # Connect to the PostgreSQL service
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "todo"
