apiVersion: v1
kind: Service
metadata:
  name: todo-web-service
spec:
  type: LoadBalancer
  selector:
    app: todo-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
